// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBF2CWP5Sb6JsE2GylokAk9c2JpVKa0g',
    appId: '1:633239572724:web:bda3179a3fd5be46eb4ea1',
    messagingSenderId: '633239572724',
    projectId: 'instagram-clone-7a4f1',
    authDomain: 'instagram-clone-7a4f1.firebaseapp.com',
    storageBucket: 'instagram-clone-7a4f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5GsJDG5R4SGf5b_mWFFKEghrKeAXCBY',
    appId: '1:633239572724:android:fd366246070c8b07eb4ea1',
    messagingSenderId: '633239572724',
    projectId: 'instagram-clone-7a4f1',
    storageBucket: 'instagram-clone-7a4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOOtlAgKNUFaep0idMvdi1C3_MH6x4Lw',
    appId: '1:633239572724:ios:1990ec6181d2b543eb4ea1',
    messagingSenderId: '633239572724',
    projectId: 'instagram-clone-7a4f1',
    storageBucket: 'instagram-clone-7a4f1.appspot.com',
    iosBundleId: 'com.example.omar',
  );
}
